version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
        requires:
          force:
            default: true
          filters:
            branches:
              only: master